apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: add
  annotations:
    sidecar.istio.io/inject: "<AUTOINJECT>"
  name: add
  namespace: <PROJECT>
spec:
  replicas: 1
  selector:
    deploymentconfig: add
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: add
        deploymentconfig: add
    spec:
      containers:
      - image: <CONTAINER>
        imagePullPolicy: Always
        name: add
        ports:
        - containerPort: 8080
          protocol: TCP
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - add
      from:
        kind: ImageStreamTag
        name: add:latest
        namespace: calculator
    type: ImageChange
  - type: ConfigChange
